#!/bin/bash

set -euo pipefail

PREFIX=/usr/local/openresty/nginx
CONF_DIR=$PREFIX/conf
GATEWAY_DIR=$CONF_DIR/gateway
SOURCE_DIR=/etc/nginx/conf.d
CANDIDATE_DIR=$GATEWAY_DIR/candidate
SNAPSHOT_DIR=$GATEWAY_DIR/snapshots
CURRENT_LINK=$GATEWAY_DIR/current
STATUS_FILE=$GATEWAY_DIR/status.json
SHADOW_PREFIX=/tmp/gateway-validate
LOGROTATE_CONF=/etc/logrotate.d/nginx
PID_FILE=/tmp/nginx.pid

LOGROTATE_FREQUENCY="${LOGROTATE_FREQUENCY:-daily}"
LOGROTATE_MAXSIZE="${LOGROTATE_MAXSIZE-1G}"
LOGROTATE_ROTATE="${LOGROTATE_ROTATE:-30}"
LOGROTATE_COMPRESS="${LOGROTATE_COMPRESS:-true}"
LOGROTATE_DELAY_SECONDS="${LOGROTATE_DELAY_SECONDS:-300}"
LOGROTATE_STATE_FILE="${LOGROTATE_STATE_FILE:-/var/log/nginx/.logrotate.status}"

GATEWAY_WATCH_CONFIG="${GATEWAY_WATCH_CONFIG:-true}"
GATEWAY_WATCH_INTERVAL="${GATEWAY_WATCH_INTERVAL:-5}"
GATEWAY_RESOLVER="${GATEWAY_RESOLVER:-}"
GATEWAY_RESOLVER_VALID="${GATEWAY_RESOLVER_VALID:-10s}"
GATEWAY_REAL_IP_FROM="${GATEWAY_REAL_IP_FROM:-}"
GATEWAY_CLIENT_MAX_BODY_SIZE="${GATEWAY_CLIENT_MAX_BODY_SIZE:-10m}"
GATEWAY_STATUS_ALLOW="${GATEWAY_STATUS_ALLOW:-127.0.0.1 ::1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 fc00::/7}"
GATEWAY_WORKER_PROCESSES="${GATEWAY_WORKER_PROCESSES:-}"
GATEWAY_WORKER_SHUTDOWN_TIMEOUT="${GATEWAY_WORKER_SHUTDOWN_TIMEOUT:-30s}"
GATEWAY_ACCESS_LOG_STDOUT="${GATEWAY_ACCESS_LOG_STDOUT:-false}"

log() {
    echo "[entrypoint] $*"
}

fail() {
    echo "[entrypoint] ERROR: $*" >&2
    exit 1
}

# --------------------------------------------------------------------------
# Environment validation: a typo must stop the container, not silently turn a
# feature off.
# --------------------------------------------------------------------------
require_match() {
    local name=$1 pattern=$2 hint=$3
    [[ "${!name}" =~ $pattern ]] || fail "$name must be $hint (got '${!name}')"
}

require_each() {
    local name=$1 pattern=$2 hint=$3 item
    for item in ${!name//,/ }; do
        [[ "$item" =~ $pattern ]] || fail "$name: '$item' is not $hint"
    done
}

validate_env() {
    local int='^[1-9][0-9]*$' bool='^(true|false)$'
    local cidr='^([0-9]{1,3}(\.[0-9]{1,3}){3}|[0-9a-fA-F:]*:[0-9a-fA-F:]*)(/[0-9]{1,3})?$'

    require_match LOGROTATE_FREQUENCY '^(hourly|daily|weekly|monthly|size)$' 'hourly, daily, weekly, monthly or size'
    require_match LOGROTATE_MAXSIZE '^([0-9]+[kMG]?)?$' 'empty or a size like 500k, 100M or 1G'
    require_match LOGROTATE_ROTATE '^[0-9]+$' 'an integer'
    require_match LOGROTATE_COMPRESS "$bool" 'true or false'
    require_match LOGROTATE_DELAY_SECONDS "$int" 'a positive integer'
    require_match GATEWAY_WATCH_CONFIG "$bool" 'true or false'
    require_match GATEWAY_WATCH_INTERVAL "$int" 'a positive integer'
    require_match GATEWAY_RESOLVER_VALID '^[0-9]+(ms|s|m|h)?$' 'a duration like 10s'
    require_match GATEWAY_CLIENT_MAX_BODY_SIZE '^[0-9]+[kKmMgG]?$' 'a size like 10m'
    require_match GATEWAY_WORKER_PROCESSES '^(auto|[1-9][0-9]*)?$' 'empty, auto or a positive integer'
    require_match GATEWAY_WORKER_SHUTDOWN_TIMEOUT '^[0-9]+(ms|s|m|h)?$' 'a duration like 30s'
    require_match GATEWAY_ACCESS_LOG_STDOUT "$bool" 'true or false'
    require_each GATEWAY_RESOLVER '^(\[[0-9a-fA-F:]+\]|[0-9.]+)(:[0-9]+)?$' 'an IP address (IPv6 in brackets)'
    require_each GATEWAY_REAL_IP_FROM "$cidr" 'an IP or CIDR'
    if [ "$GATEWAY_STATUS_ALLOW" != "all" ]; then
        require_each GATEWAY_STATUS_ALLOW "$cidr" 'an IP or CIDR (or set the whole variable to "all")'
    fi
    if [ "$LOGROTATE_FREQUENCY" = "size" ] && [ -z "$LOGROTATE_MAXSIZE" ]; then
        fail "LOGROTATE_FREQUENCY=size requires LOGROTATE_MAXSIZE"
    fi
}

# --------------------------------------------------------------------------
# Rendered nginx fragments
# --------------------------------------------------------------------------

# First nameserver from resolv.conf (Docker's embedded DNS on user networks,
# CoreDNS on Kubernetes). IPv6 addresses need brackets in nginx.
detect_resolver() {
    local ns
    ns=$(awk '/^nameserver/ { print $2; exit }' /etc/resolv.conf)
    [ -n "$ns" ] || return 1
    case "$ns" in
        *:*) echo "[$ns]" ;;
        *)   echo "$ns" ;;
    esac
}

# worker_processes auto counts the host CPUs, not the container limit, so a
# 2-CPU container on a 64-core node would start 64 throttled workers.
detect_workers() {
    local quota period
    if [ -r /sys/fs/cgroup/cpu.max ]; then
        read -r quota period < /sys/fs/cgroup/cpu.max
        if [ "$quota" != "max" ]; then
            echo $(( (quota + period - 1) / period ))
            return
        fi
    fi
    echo auto
}

render_main_conf() {
    local workers="${GATEWAY_WORKER_PROCESSES:-$(detect_workers)}"
    {
        echo "# Generated by entrypoint.sh at startup — edits are overwritten."
        echo "worker_processes ${workers};"
        echo "worker_shutdown_timeout ${GATEWAY_WORKER_SHUTDOWN_TIMEOUT};"
    } > "$GATEWAY_DIR/main.conf"
    log "worker_processes=${workers} worker_shutdown_timeout=${GATEWAY_WORKER_SHUTDOWN_TIMEOUT}"
}

render_runtime_conf() {
    local resolver="$GATEWAY_RESOLVER" stdout_log=0 cidr
    if [ -z "$resolver" ]; then
        resolver=$(detect_resolver) || fail "no nameserver in /etc/resolv.conf; set GATEWAY_RESOLVER"
    fi
    if [ "$GATEWAY_ACCESS_LOG_STDOUT" = "true" ]; then
        stdout_log=1
    fi

    {
        echo "# Generated by entrypoint.sh at startup — edits are overwritten."
        echo "resolver ${resolver} valid=${GATEWAY_RESOLVER_VALID} ipv6=off;"
        echo "resolver_timeout 5s;"
        echo "client_max_body_size ${GATEWAY_CLIENT_MAX_BODY_SIZE};"
        echo "map \$remote_addr \$gateway_log_stdout { default ${stdout_log}; }"
        if [ -n "$GATEWAY_REAL_IP_FROM" ]; then
            # Behind trusted proxies: recover the client IP and keep the chain.
            for cidr in ${GATEWAY_REAL_IP_FROM//,/ }; do
                echo "set_real_ip_from ${cidr};"
            done
            echo "real_ip_header X-Forwarded-For;"
            echo "real_ip_recursive on;"
            echo "map \$remote_addr \$gateway_forwarded_for { default \$proxy_add_x_forwarded_for; }"
            echo "map \$http_x_forwarded_proto \$gateway_forwarded_proto { \"~^https?\$\" \$http_x_forwarded_proto; default \$scheme; }"
        else
            # The gateway is the edge: client-supplied X-Forwarded-* are lies.
            echo "map \$remote_addr \$gateway_forwarded_for { default \$remote_addr; }"
            echo "map \$remote_addr \$gateway_forwarded_proto { default \$scheme; }"
        fi
    } > "$GATEWAY_DIR/runtime.conf"

    {
        echo "# Generated by entrypoint.sh at startup — edits are overwritten."
        if [ "$GATEWAY_STATUS_ALLOW" != "all" ]; then
            for cidr in ${GATEWAY_STATUS_ALLOW//,/ }; do
                echo "allow ${cidr};"
            done
            echo "deny all;"
        fi
    } > "$GATEWAY_DIR/status-allow.conf"

    log "resolver=${resolver} client_max_body_size=${GATEWAY_CLIENT_MAX_BODY_SIZE} real_ip_from=${GATEWAY_REAL_IP_FROM:-<none: edge mode>} status_allow=${GATEWAY_STATUS_ALLOW}"
}

# --------------------------------------------------------------------------
# Log rotation
#   hourly|daily|weekly|monthly  rotate on that schedule, and earlier whenever a
#                                file exceeds LOGROTATE_MAXSIZE (empty = never early)
#   size                         rotate only when a file exceeds LOGROTATE_MAXSIZE
# --------------------------------------------------------------------------
render_logrotate_conf() {
    local trigger compression="    nocompress"
    if [ "$LOGROTATE_FREQUENCY" = "size" ]; then
        trigger="    size ${LOGROTATE_MAXSIZE}"
    else
        trigger="    ${LOGROTATE_FREQUENCY}"
        if [ -n "$LOGROTATE_MAXSIZE" ]; then
            trigger+=$'\n'"    maxsize ${LOGROTATE_MAXSIZE}"
        fi
    fi
    if [ "$LOGROTATE_COMPRESS" = "true" ]; then
        compression=$'    compress\n    delaycompress'
    fi

    cat > "$LOGROTATE_CONF" <<EOF
/var/log/nginx/*.log /var/log/nginx/*/*.log {
${trigger}
    rotate ${LOGROTATE_ROTATE}
${compression}
    missingok
    notifempty
    dateext
    dateformat -%Y%m%d-%s
    create 0640
    sharedscripts
    postrotate
        [ -f ${PID_FILE} ] && kill -USR1 \$(cat ${PID_FILE}) || true
    endscript
}
EOF
    log "logrotate: frequency=${LOGROTATE_FREQUENCY} maxsize=${LOGROTATE_MAXSIZE:-<none>} keep=${LOGROTATE_ROTATE} compress=${LOGROTATE_COMPRESS} check_every=${LOGROTATE_DELAY_SECONDS}s"
}

# logrotate decides from its state file whether a rotation is due, so the loop
# only needs to check often enough for the smallest trigger. Never pass -f:
# forcing would rotate on every check regardless of frequency or size.
logrotate_loop() {
    while sleep "$LOGROTATE_DELAY_SECONDS"; do
        /usr/sbin/logrotate -s "$LOGROTATE_STATE_FILE" "$LOGROTATE_CONF" \
            || log "logrotate exited with an error"
    done
}

# --------------------------------------------------------------------------
# Config publishing with a last known-good snapshot
#
# conf/routes -> gateway/current -> gateway/snapshots/<id>. A change in
# /etc/nginx/conf.d is copied to gateway/candidate and validated inside a
# shadow prefix that is identical to the real one except that routes/ points
# at the candidate. Only a candidate that passes is published, by swapping the
# `current` symlink atomically, and only then is nginx reloaded.
# --------------------------------------------------------------------------
build_shadow_prefix() {
    local entry
    rm -rf "$SHADOW_PREFIX"
    mkdir -p "$SHADOW_PREFIX/conf/gateway" "$SHADOW_PREFIX/logs"
    ln -s "$PREFIX/modules" "$SHADOW_PREFIX/modules"
    for entry in "$CONF_DIR"/*; do
        case "${entry##*/}" in
            gateway|routes) ;;
            *) ln -s "$entry" "$SHADOW_PREFIX/conf/${entry##*/}" ;;
        esac
    done
    for entry in main.conf runtime.conf status-allow.conf; do
        ln -s "$GATEWAY_DIR/$entry" "$SHADOW_PREFIX/conf/gateway/$entry"
    done
    ln -s "$CANDIDATE_DIR" "$SHADOW_PREFIX/conf/routes"
}

write_status() {
    local state=$1 message=$2 snapshot
    snapshot=$(readlink "$CURRENT_LINK" 2>/dev/null || true)
    printf '{"state":"%s","message":"%s","checked_at":%s,"snapshot":"%s"}\n' \
        "$state" "$message" "$(date +%s)" "${snapshot##*/}" > "$STATUS_FILE.tmp"
    mv -f "$STATUS_FILE.tmp" "$STATUS_FILE"
}

stage_candidate() {
    rm -rf "$CANDIDATE_DIR"
    mkdir -p "$CANDIDATE_DIR"
    # -L dereferences Kubernetes ConfigMap symlinks into plain files.
    cp -RL "$SOURCE_DIR/." "$CANDIDATE_DIR/"
}

validate_candidate() {
    openresty -t -q -p "$SHADOW_PREFIX/" -c "$SHADOW_PREFIX/conf/nginx.conf" \
        && resty -e "os.exit(require('gateway.validate').run('$CANDIDATE_DIR') and 0 or 1)"
}

publish_candidate() {
    local id old
    id=$(date +%s%N)
    mkdir -p "$SNAPSHOT_DIR"
    mv "$CANDIDATE_DIR" "$SNAPSHOT_DIR/$id"
    ln -sfn "snapshots/$id" "$CURRENT_LINK.tmp"
    mv -T "$CURRENT_LINK.tmp" "$CURRENT_LINK"
    # Keep the published snapshot and the one before it.
    for old in $(ls -1 "$SNAPSHOT_DIR" | sort -n | head -n -2); do
        rm -rf "${SNAPSHOT_DIR:?}/$old"
    done
}

config_fingerprint() {
    find -L "$SOURCE_DIR" -type f -print0 2>/dev/null | sort -z | xargs -0 -r md5sum 2>/dev/null | md5sum
}

# Runs without errexit: a transient failure (a file vanishing mid-scan during
# a ConfigMap swap) must skip one cycle, never kill the watcher.
watch_config() {
    set +e +o pipefail
    local last=$INITIAL_FINGERPRINT current
    while sleep "$GATEWAY_WATCH_INTERVAL"; do
        current=$(config_fingerprint)
        [ -n "$current" ] && [ "$current" != "$last" ] || continue
        last=$current
        if stage_candidate && validate_candidate; then
            publish_candidate
            if openresty -s reload; then
                write_status valid "published and reloaded"
                log "configuration changed, published and reloaded"
            else
                write_status fallback "reload signal failed"
                log "configuration published but the reload signal FAILED"
            fi
        else
            write_status fallback "conf.d is invalid; serving the last known-good snapshot"
            log "configuration changed but is INVALID, still serving the last known-good snapshot"
        fi
    done
}

# --------------------------------------------------------------------------
# Startup
# --------------------------------------------------------------------------
validate_env
render_main_conf
render_runtime_conf
render_logrotate_conf
build_shadow_prefix

# Taken before the startup publish so an edit made while it runs is still
# seen as a change by the watcher.
INITIAL_FINGERPRINT=$(config_fingerprint || true)

log "validating ${SOURCE_DIR}..."
if stage_candidate && validate_candidate; then
    publish_candidate
    write_status valid "published at startup"
elif [ -e "$CURRENT_LINK" ]; then
    write_status fallback "conf.d is invalid; serving the last known-good snapshot"
    log "WARNING: ${SOURCE_DIR} is INVALID; starting with the last known-good snapshot $(readlink "$CURRENT_LINK")"
else
    fail "${SOURCE_DIR} is invalid and there is no previous known-good snapshot to fall back to"
fi
openresty -t -q || fail "the published configuration does not pass openresty -t"

( set +e +o pipefail; logrotate_loop ) &
if [ "$GATEWAY_WATCH_CONFIG" = "true" ]; then
    log "watching ${SOURCE_DIR} every ${GATEWAY_WATCH_INTERVAL}s for changes"
    watch_config &
fi

openresty -g "daemon off;" &
nginx_pid=$!

# Graceful stop: in-flight requests get up to GATEWAY_WORKER_SHUTDOWN_TIMEOUT.
# Give the orchestrator a longer stop grace period than that.
shutdown() {
    log "stopping gracefully..."
    openresty -s quit || kill -QUIT "$nginx_pid"
    wait "$nginx_pid" || true
    exit 0
}
trap shutdown SIGTERM SIGINT SIGQUIT

log "$(openresty -v 2>&1) started (status :8081)"
wait "$nginx_pid"
