#!/bin/bash

set -euo pipefail

CONF_DIR=/etc/nginx/conf.d
RUNTIME_CONF=/usr/local/openresty/nginx/conf/gateway/runtime.conf
LOGROTATE_CONF=/etc/logrotate.d/nginx
PID_FILE=/tmp/nginx.pid

LOGROTATE_FREQUENCY="${LOGROTATE_FREQUENCY:-daily}"
LOGROTATE_MAXSIZE="${LOGROTATE_MAXSIZE-1G}"
LOGROTATE_ROTATE="${LOGROTATE_ROTATE:-30}"
LOGROTATE_COMPRESS="${LOGROTATE_COMPRESS:-true}"
LOGROTATE_DELAY_SECONDS="${LOGROTATE_DELAY_SECONDS:-300}"
LOGROTATE_STATE_FILE="${LOGROTATE_STATE_FILE:-/var/log/nginx/.logrotate.status}"

GATEWAY_WATCH_CONFIG="${GATEWAY_WATCH_CONFIG:-true}"
GATEWAY_WATCH_INTERVAL="${GATEWAY_WATCH_INTERVAL:-5}"
GATEWAY_RESOLVER="${GATEWAY_RESOLVER:-}"
GATEWAY_RESOLVER_VALID="${GATEWAY_RESOLVER_VALID:-10s}"
GATEWAY_REAL_IP_FROM="${GATEWAY_REAL_IP_FROM:-}"
GATEWAY_CLIENT_MAX_BODY_SIZE="${GATEWAY_CLIENT_MAX_BODY_SIZE:-10m}"

log() {
    echo "[entrypoint] $*"
}

fail() {
    echo "[entrypoint] ERROR: $*" >&2
    exit 1
}

# First nameserver from resolv.conf (Docker's embedded DNS on user networks,
# CoreDNS on Kubernetes). IPv6 addresses need brackets in nginx.
detect_resolver() {
    local ns
    ns=$(awk '/^nameserver/ { print $2; exit }' /etc/resolv.conf)
    [ -n "$ns" ] || fail "no nameserver in /etc/resolv.conf; set GATEWAY_RESOLVER"
    case "$ns" in
        *:*) echo "[$ns]" ;;
        *)   echo "$ns" ;;
    esac
}

render_runtime_conf() {
    local resolver="${GATEWAY_RESOLVER:-$(detect_resolver)}"
    {
        echo "# Generated by entrypoint.sh at startup — edits are overwritten."
        echo "resolver ${resolver} valid=${GATEWAY_RESOLVER_VALID} ipv6=off;"
        echo "resolver_timeout 5s;"
        echo "client_max_body_size ${GATEWAY_CLIENT_MAX_BODY_SIZE};"
        if [ -n "$GATEWAY_REAL_IP_FROM" ]; then
            local cidr
            for cidr in ${GATEWAY_REAL_IP_FROM//,/ }; do
                echo "set_real_ip_from ${cidr};"
            done
            echo "real_ip_header X-Forwarded-For;"
            echo "real_ip_recursive on;"
        fi
    } > "$RUNTIME_CONF"
    log "resolver=${resolver} client_max_body_size=${GATEWAY_CLIENT_MAX_BODY_SIZE} real_ip_from=${GATEWAY_REAL_IP_FROM:-<none>}"
}

# Rotation triggers:
#   hourly|daily|weekly|monthly  rotate on that schedule, and earlier whenever a
#                                file exceeds LOGROTATE_MAXSIZE (empty = never early)
#   size                         rotate only when a file exceeds LOGROTATE_MAXSIZE
render_logrotate_conf() {
    local trigger
    case "$LOGROTATE_FREQUENCY" in
        hourly|daily|weekly|monthly)
            trigger="    ${LOGROTATE_FREQUENCY}"
            if [ -n "$LOGROTATE_MAXSIZE" ]; then
                trigger+=$'\n'"    maxsize ${LOGROTATE_MAXSIZE}"
            fi
            ;;
        size)
            [ -n "$LOGROTATE_MAXSIZE" ] || fail "LOGROTATE_FREQUENCY=size requires LOGROTATE_MAXSIZE"
            trigger="    size ${LOGROTATE_MAXSIZE}"
            ;;
        *)
            fail "LOGROTATE_FREQUENCY must be hourly, daily, weekly, monthly or size (got '${LOGROTATE_FREQUENCY}')"
            ;;
    esac
    [[ -z "$LOGROTATE_MAXSIZE" || "$LOGROTATE_MAXSIZE" =~ ^[0-9]+[kMG]?$ ]] \
        || fail "LOGROTATE_MAXSIZE must look like 500k, 100M or 1G (got '${LOGROTATE_MAXSIZE}')"
    [[ "$LOGROTATE_ROTATE" =~ ^[0-9]+$ ]] || fail "LOGROTATE_ROTATE must be an integer"

    local compression="    nocompress"
    if [ "$LOGROTATE_COMPRESS" = "true" ]; then
        compression=$'    compress\n    delaycompress'
    fi

    cat > "$LOGROTATE_CONF" <<EOF
/var/log/nginx/*.log /var/log/nginx/*/*.log {
${trigger}
    rotate ${LOGROTATE_ROTATE}
${compression}
    missingok
    notifempty
    dateext
    dateformat -%Y%m%d-%s
    create 0640
    sharedscripts
    postrotate
        [ -f ${PID_FILE} ] && kill -USR1 \$(cat ${PID_FILE}) || true
    endscript
}
EOF
    log "logrotate: frequency=${LOGROTATE_FREQUENCY} maxsize=${LOGROTATE_MAXSIZE:-<none>} keep=${LOGROTATE_ROTATE} compress=${LOGROTATE_COMPRESS} check_every=${LOGROTATE_DELAY_SECONDS}s"
}

# logrotate decides from its state file whether a rotation is due, so the loop
# only needs to check often enough for the smallest trigger. Never pass -f:
# forcing would rotate on every check regardless of frequency or size.
logrotate_loop() {
    while sleep "$LOGROTATE_DELAY_SECONDS"; do
        /usr/sbin/logrotate -s "$LOGROTATE_STATE_FILE" "$LOGROTATE_CONF" \
            || log "logrotate exited with an error"
    done
}

config_fingerprint() {
    find -L "$CONF_DIR" -type f -exec md5sum {} + 2>/dev/null | sort | md5sum
}

# File-provider style hot reload: when anything under conf.d changes, validate
# first and reload only a config that passes, so a bad edit never takes the
# gateway down.
watch_config() {
    local last current
    last=$(config_fingerprint)
    while sleep "$GATEWAY_WATCH_INTERVAL"; do
        current=$(config_fingerprint)
        [ "$current" = "$last" ] && continue
        last=$current
        if openresty -t -q; then
            openresty -s reload
            log "configuration changed, reloaded"
        else
            log "configuration changed but is INVALID, keeping the running one"
        fi
    done
}

render_runtime_conf
render_logrotate_conf

log "validating configuration..."
openresty -t || fail "invalid configuration"

logrotate_loop &
if [ "$GATEWAY_WATCH_CONFIG" = "true" ]; then
    log "watching ${CONF_DIR} every ${GATEWAY_WATCH_INTERVAL}s for changes"
    watch_config &
fi

openresty -g "daemon off;" &
nginx_pid=$!

# Graceful stop: let in-flight requests finish before the container exits.
shutdown() {
    log "stopping gracefully..."
    openresty -s quit || kill -QUIT "$nginx_pid"
    wait "$nginx_pid" || true
    exit 0
}
trap shutdown SIGTERM SIGINT SIGQUIT

log "$(openresty -v 2>&1) started (http :8080, status :8081)"
wait "$nginx_pid"
